server:
  port: 8080

spring:
  profiles:
    active: local

# jwt
jwt:
  secretKey: JwtSuperSecretKey
  accessToken:
    expiresInDay: 7
  refreshToken:
    expiresInDay: 30

myapp:
  adminEmail: admin@admin.com
  adminPassword: adminPassword
  userEmail: user@user.com
  userPassword: userPassword


