
# jpa 및 database 설정
spring:
  profiles: local
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
    url: jdbc:h2:~/test

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

# actuator 설정
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

  info:
    git:
      enabled: true
      mode: full

  endpoint:
    health:
      enabled: true
      show-details: always
