spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    initialization-mode: always
    dbcp2:
      validation-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
